export const PUNISHMENTS = [
    "Baila la Macarena durante 10 segundos",
    "Confiesa tu mayor miedo irracional",
    "Imita a un animal elegido por el grupo",
    "Canta el estribillo de tu canción favorita",
    "Habla con acento extranjero hasta tu próximo turno",
    "Haz 5 sentadillas ahora mismo",
    "Di el alfabeto al revés (inténtalo)",
    "Cuenta un chiste malo obligatoriamente",
    "Haz una pose de superhéroe y mantenla 10 segundos",
    "Narra todo lo que haces como si fuera un documental",
    "Haz mímica de tu película favorita hasta que la adivinen",
    "Bebe un vaso de agua sin usar las manos",
    "Hazte una foto haciendo una mueca horrible y enséñala",
    "Deja que el grupo elija tu próximo avatar",
    "Habla susurrando durante 3 rondas",
    "No puedes usar la letra 'E' en tu próxima respuesta",
    "Haz como que estás en una montaña rusa",
    "Imita a otro jugador del grupo",
    "Haz ruidos de animal cada vez que hables",
    "Declara tu amor eterno a un objeto inanimado",
    "Baila sin música lo más sexy que puedas",
    "Haz como si fueras un bebé llorando",
    "Intenta lamerte el codo (spoiler: no podrás)",
    "Haz 10 saltos de tijera",
    "Canta una canción infantil con voz de ópera",
    "Haz una cara de pez y mantenla 15 segundos",
    "Camina por la habitación como un cangrejo",
    "Hazte el muerto de manera dramática",
    "Finge que estás en un anuncio de teletienda",
    "Haz beatbox durante 10 segundos",
    "Lee el último mensaje de WhatsApp que recibiste",
    "Enseña tu foto más vergonzosa de la galería",
    "Di 3 cosas buenas de la persona que tienes a la izquierda",
    "Haz de comentarista deportivo de lo que está pasando",
    "Finge que eres un robot averiado",
    "Grita '¡Soy el rey del mundo!' por la ventana (o bajito)",
    "Haz la gallina",
    "Imita a Shakira cantando",
    "Haz de estatua durante 1 minuto (si te mueves, repites)",
    "Habla con la lengua fuera",
    "Canta el cumpleaños feliz a nadie en particular",
    "Haz cosquillas al aire",
    "Finge que te electrocutas",
    "Haz un desfile de moda por el pasillo",
    "Pon cara de haber chupado un limón",
    "Intenta tocarte la nariz con la lengua",
    "Haz el pino (o inténtalo con cuidado)",
    "Baila twerking (o intentalo)",
    "Haz de mimo atrapado en una caja",
    "Finge ser un influencer grabando un story",
    "Habla todo el rato con rimas",
    "Haz de zombi hambriento",
    "Gira sobre ti mismo 10 veces y trata de caminar recto",
    "Haz burpees hasta que alguien diga 'basta' (max 5)",
    "Canta una canción de reggaeton como si fuera poesía",
    "Haz de árbitro de fútbol enfadado",
    "Imita a tu madre enfadada",
    "Haz de gato pidiendo comida",
    "Finge que tienes una pulga en la espalda",
    "Haz de presentador de noticias muy serio",
    "Baila el robot",
    "Finge que estás en cámara lenta",
    "Haz una imitación de Gollum",
    "Canta 'Libre Soy' de Frozen",
    "Haz de camarero torpe",
    "Finge que te persigue una abeja",
    "Haz de director de orquesta loco",
    "Canta una canción en un idioma inventado",
    "Finge que estás masticando un chicle gigante",
    "Haz de vampiro despertando",
    "Haz de tenista profesional gritando al golpear",
    "Finge que estás en gravedad cero",
    "Haz de mono buscando piojos",
    "imita la risa de Bob Esponja",
    "Finge que eres un T-Rex",
    "Baila salsa con una escoba (o aire)",
    "Haz de abuelo contando batallitas",
    "Finge que te estás derritiendo",
    "Haz de rapero malísimo",
    "Finge que te ha tocado la lotería",
    "Haz de ninja sigiloso (y falla estrepitosamente)",
    "Finge que eres un pez fuera del agua",
    "Haz de estatua de la libertad",
    "Finge que estás en un terremoto",
    "Haz de bruja riendo",
    "Finge que te pesa mucho la cabeza",
    "Haz de levantador de pesas olímpico",
    "Finge que estás comiendo algo súper picante",
    "Haz de mimo tirando de una cuerda",
    "Finge que eres un globo desinflándose",
    "Haz de DJ en una fiesta loca",
    "Finge que estás en una película de terror",
    "Haz de detective buscando pistas",
    "Finge que eres un piloto de fórmula 1",
    "Haz de vaquero en un duelo",
    "Finge que eres un maratoniano llegando a meta",
    "Haz de político dando un discurso",
    "Finge que eres un chef probando tu plato",
    "Haz de cantante de rock rompiendo una guitarra",
    "Finge que eres un bebé probando limón"
];
