export const SHAME_PHRASES = [
    "Me hago caca y no llego",
    "A veces me huelen los pies y me gusta",
    "Duermo con un peluche y le cuento mis secretos",
    "He usado el mismo calzoncillo 3 días seguidos",
    "Creo que la Tierra es plana (es broma, ¿o no?)",
    "Me hurgo la nariz cuando nadie mira",
    "Aún no me sé la tabla del 9",
    "Lloro con los anuncios de perritos",
    "Me da miedo la oscuridad",
    "Tengo un crush con un personaje de dibujos animados",
    "Hablo con mis plantas y me responden",
    "Me comí un moco la semana pasada",
    "A veces finjo que hablo por teléfono para no saludar",
    "Me asusto de mi propia sombra",
    "No me he duchado hoy (y se nota)",
    "Me gusta oler mis propios pedos",
    "Creo que soy adoptado por alienígenas",
    "He buscado mi nombre en Google 10 veces hoy",
    "A veces lamo el plato cuando termino de comer",
    "Le hablo a mi microondas para que vaya más rápido",
    "Me da miedo el monstruo de debajo de la cama",
    "Todavía veo dibujos animados los sábados por la mañana",
    "Me he tirado un pedo y he culpado al perro",
    "Se me ha olvidado cómo se atan los zapatos",
    "Pies que huelen a queso, mi pasión secreta",
    "Me he reído de un chiste que no entendí",
    "He mandado un WhatsApp criticando a alguien a esa misma persona",
    "Me he chocado contra una puerta de cristal",
    "He saludado a un maniquí pensando que era una persona",
    "Me he puesto la ropa interior al revés",
    "He intentado desbloquear mi casa con el mando del coche",
    "He buscado las gafas teniéndolas puestas",
    "He llamado 'mamá' a mi profesora/jefe",
    "He cantado en la ducha creyendo que nadie me oía (y me oían)",
    "Me he caído subiendo escaleras (es difícil, lo sé)",
    "He escupido al hablar y le ha dado a alguien",
    "He tenido comida en los dientes todo el día y nadie me lo dijo",
    "He roncado en el cine y me he despertado a mí mismo",
    "Me he puesto a llorar porque se me cayó un helado",
    "He intentado hacer zoom en una revista de papel",
    "He dado like a una foto de mi ex de hace 3 años sin querer",
    "He confundido a un desconocido con un amigo y le he abrazado",
    "Me he tirado el café encima en una reunión",
    "He andado con el papel higiénico pegado al zapato",
    "He dicho 'igualmente' cuando me dijeron 'buen viaje' (y yo no viajaba)",
    "He intentado pagar con la tarjeta del gimnasio",
    "Me he quedado dormido en el baño del trabajo",
    "He hablado a un perro con voz de bebé delante de mi jefe",
    "He bailado solo en el ascensor y me ha visto la cámara",
    "He hecho photobomb en una boda sin conocer a los novios",
    "He contado un secreto en voz alta pensando que susurraba",
    "Me he reído en un momento serio y no podía parar",
    "He dicho 'te quiero' al repartidor de pizza",
    "He intentado abrir una puerta automática empujando",
    "He saludado a alguien que saludaba al de atrás",
    "He tropezado con mis propios pies estando quieto",
    "He bebido del vaso de otra persona por error",
    "Me he puesto los calcetines desparejados a propósito",
    "He fingido saber de vinos y era Don Simón",
    "He aplaudido el primero y nadie me siguió",
    "He pregutnado '¿qué?' tres veces y sigo sin entender",
    "He intentado entrar en el coche equivocado",
    "He dicho mal mi propio nombre de los nervios",
    "He felicitado a alguien que no cumplía años",
    "He contado el final de la película sin querer",
    "Me he asustado con mi propio reflejo",
    "He ido al baño de mujeres/hombres por error",
    "He comido comida de perro por curiosidad",
    "He intentado 'guardar partida' en la vida real",
    "He hablado con un bot pensando que era una persona",
    "He buscado el móvil con la linterna del móvil",
    "He intentado pasar la página de un libro deslizando el dedo",
    "He soplado al helado porque estaba frío",
    "He pedido perdón a una mesa por chocarme",
    "He intentado arrancar el coche con el mando de la tele",
    "He echado sal al café en vez de azúcar",
    "He guardado el mando de la tele en la nevera",
    "He tirado la cucharilla a la basura y el yogur al fregadero",
    "He intentado abrir mi casa con la tarjeta del metro",
    "He contestado al teléfono con el mando a distancia",
    "He buscado las llaves teniéndolas en la mano",
    "He intentado subir el volumen de mi pareja con un mando imaginarío",
    "He esperado un stop a que se pusiera en verde",
    "He soplado a la comida picante para 'enfriar' el picante",
    "He intentado hacer ctrl+z en un examen escrito",
    "He saludado a mi propio perro por videollamada",
    "He preguntado si el agua con gas tiene gluten",
    "He dicho 'gracias' al cajero automático",
    "He intentado hacer scroll en un periódico",
    "He dado las buenas noches a las 10 de la mañana",
    "He confundido un calabacín con un pepino",
    "He intentado beber con la mascarilla puesta",
    "He chocado los cinco a un camarero que traía la bandeja",
    "He cantado la letra equivocada muy fuerte",
    "He dicho 'provecho' en un baño",
    "He intentado pagar en euros en un viaje a Londres",
    "He llamado al perro por el nombre de mi pareja",
    "He intentado encender la luz de una habitación que no tiene luz",
    "He puesto el lavavajillas sin pastilla"
];
